### ISSUE TITLE
вывод значений в переменную

### ISSUE THREAD

**Issue by localcreator** [cia76/QuikPy#1]
Здравствуйте! Благодарю за большой вклад в создание и развитие коннектора, а так же за шикарные примеры! Вопрос по Stream.py - можете показать пример, каким образом полученные значения по подписке можно сохранять в переменной, вместо того чтобы печатать в консоле? Правильно будет просто поместить глобальную переменную в PrintCallback, которая будет собирать данные?

**Comment by cia76** [comment]
Я бы сделал отдельный класс, где при инициализации задал бы все нужные переменные. Там же прописал бы и аналог PrintCallback, где бы новые значения заносил в список или ряд данных.

С другой стороны, есть уже готовые решения, где много инфраструктурных вещей уже сделано. Например, BackTrader. [Мой провайдер Квика для BackTrader находится здесь](https://github.com/cia76/BackTraderQuik).
