### ISSUE TITLE
Не все выводит по запросу по опционам

### ISSUE THREAD

**Issue by Alkor135** [cia76/QuikPy#10]
Здравствуйте!
Спасибо за прекрасную библиотеку!!!
У меня не все запросы обрабатываются по опционам
`
    ba = qpProvider.GetParamEx(classCode, secCode, 'OPTIONBASE')['data']['param_value']  # Базовый актив
    option_type = qpProvider.GetParamEx(classCode, secCode, 'OPTIONTYPE')['data']['param_value']
    long_name = qpProvider.GetParamEx(classCode, secCode, 'LONGNAME')['data']['param_value']  # Длинное имя
    print(f'{ba=}, {option_type=}, {long_name=}')  # Не работает, выводит '0.000000'
`
Полный код https://pastebin.com/bXa9aVqh

**Comment by cia76** [comment]
Добрый день!

Как можно решить этот вопрос.
1. Проверить, что по запросам, действительно у брокера и в Квике находится нужная информация. Бывает, что в документации написано одно, а брокер идет своим особым путем, о чем нас не уведомляет. Техподдержка брокера в таком случае должна помочь.
2. В Квике мы работаем с таблицами. Попробуйте вывести то, что вы хотите в виде таблицы. Посмотрите ее поля. Возможно данные есть, просто поле по другому называется.

Через GetParamEx просто вызываем поле из таблицы Квика.

**Comment by Alkor135** [comment]
В том то и дело, что названия полей взяты из DDE выгрузки таблицы. В Excel данные есть, а скрипт данные не выводит.

**Comment by cia76** [comment]
Не все то, что Квик выдает в Excel, он выдает через LUA скрипты. Нужно спросить на форуме Квика, можно ли через LUA получить данные нужной вам таблицы и нужного вам поля. По [вот этой теме](https://forum.quik.ru/forum10/topic4401/) видно, что экспорта доски опционов через LUA нет.
