### ISSUE TITLE
qpProvider.GetFuturesHoldings() error

### ISSUE THREAD

**Issue by Rilin** [cia76/QuikPy#11]
Добрый вечер!

в "02 - Accounts.py" [Examples]
функция qpProvider.GetFuturesHoldings() выдает ошибку:

{'lua_error': "Lua error: D:\\QUIK\\SBERBANK\\lua\\qsfunctions.lua:642: attempt to perform arithmetic on a nil value (local 'posType')", 'data': '', 'id': 0, 'cmd': 'lua_error', 't': ''}

Подскажите пожалуйста, где можно посмотреть. В Quik:
![image](https://user-images.githubusercontent.com/3840279/210437601-38eabf66-8416-45e5-a812-99293097cffc.png)

OnFuturesClientHolding() отрабатывает нормально, все показывает

P.S.
![image](https://user-images.githubusercontent.com/3840279/210605261-3b5ec2e2-9e03-4601-a11d-ae87b321a373.png)

в Исходнике подчеркнутое исправил на "getFuturesClientHoldings" - заработало. Ошибка ?

**Comment by cia76** [comment]
Да, опечатка вышла. Исправил в коде. Благодарю!
