### ISSUE TITLE
Обработка событий после разрыва связи

### ISSUE THREAD

**Issue by vzhilov** [cia76/QuikPy#14]
Здравствуйте!

Запускаю свой скрипт подключения к QUIK из Jupyter Notebook. Скрипт работает и получает данные из QUIK должным образом. Однако, если в процессе работы разорвать подключение QUIK с сервером и затем установить связь снова, то QUIK зависает до тех пор пока вручную не отключить скрипт. Это особенно актуально когда ночью брокер перегружает сервера, соединение рвется и, соответственно, с утра после автоматического реконнекта настроенного в Quik он виснет, пока свой скрипт не перезапустишь. 

Вот мой скрипт:

```
qp = QuikPy()
qp.OnNewCandle = handler
print(f'Подключено к терминалу QUIK по адресу: {qp.Host}:{qp.RequestsPort},{qp.CallbacksPort}')
print(f'Подписка на интервал 1:', qp.SubscribeToCandles('TQBR', 'SBER', 1)['data'])

while True:
    pass

```

**Comment by cia76** [comment]
Добрый день!

Что рекомендую сделать. На все случаи жизни у меня написаны примеры. Запустите скрипт 05_Stream.py из IDLE /  PyCharm / Visual Studio Code... Посмотрите как он работает при отключении/подключении QUIK. Если все работает, то ошибку ищите в Jupyter Notebook.

**Comment by vzhilov** [comment]
Да, Вы правы, ваши примеры проходят без этой ошибки. Оказалось проблема в моей функции handler, которая обрабатывает новые входящие свечки. Однако, при первом соединении в эту функцию выдаются сразу все минутные свечки за последние 10 дней. Я такого не ожидал, и в результате функция зависала. Сейчас поставил проверку на актуальность каждой свечки и проблема решилась.
