### ISSUE TITLE
Получение общей ликвидационной стоимости портфеля

### ISSUE THREAD

**Issue by vzhilov** [cia76/QuikPy#16]
Здравствуйте! Просмотрел [Ваш пример](https://github.com/cia76/QuikPy/blob/master/Examples/02_Accounts.py) по получению информации по счетам, но не смог использовать его для получения `Суммарной оценки стоимости позиций по ликвидационной цене`. Это итоговый параметр таблицы `Состояние счета` (Отображение позиций клиента по инструментам). Данный параметр отображает реальную сумму средств, которыми распологает клиент в валюте и инструментах без учета займов. 

Отображается внизу таблицы (`Ликв. ст-ть: 461 765.10`)

![Таблица Состояния счета](https://s3.open-broker.ru/site/journals/images/gk6DQMWdhRr3xPN6Df7x0tdyxlFLCzzPZCs4JSeo.png)

Возможно ли эту цифру получить при помощи вашей библиотеки?

**Comment by cia76** [comment]
Добрый день!

Библиотека QuikPy построена на основе [официальной документации по языку LUA в QUIK](https://arqatech.com/ru/support/files/) В ней понятие ликвидационной стоимости не нашел. Возможно, что-то пропустил... Если она там есть, то, конечно, ее можно получить и обработатать. В вашем случае взять каждую бумагу и просуммировать поле ликв. стоимость.

**Comment by vzhilov** [comment]
Здравствуйте!

Да, есть такое в документации. 

Раздел 3. Просмотр информации, 
-->глава 3.5 Состояние счета, 
---->3.5.3 Вкладка «Позиции»
------>Итоговые параметры таблицы

Третий по счету параметр:

> Ликв. ст-ть -- Суммарная оценка стоимости позиций по ликвидационной цене (по значению 
> параметра Ликв.стоимость) с точностью валюты, выбранной в настройках.
> Для срочного рынка: суммарная оценка стоимости позиций по 
> ликвидационной цене, ГО и вариационной маржи

Насколько я понял, это единственный параметр, который отображает сколько реально на счетах есть денег, если, скажем, продать все активы и выйти в кэш. По нему можно отслеживать эффективность стратегии в любой момент времени.

**Comment by cia76** [comment]
Понятно, что в документации есть все колонки таблиц. Но не все колонки можно получить через LUA. Я посмотрел документацию:
- Интерпретатор языка Lua
- Использование Lua в Рабочем месте QUIK

Там этот параметр не нашел.

В проекте BackTraderQuik мы получаем свободные средства по счету и стоимость позиций по счету. Файл QKBroker.py строки 164-227. Сумма этих значений и будет ликвидационная ст-ть портфеля.

**Comment by vzhilov** [comment]
Спасибо за подсказку, выходит что это единственный вариант. Так же пока и сделал.
