### ISSUE TITLE
Как переписать QuikPy под Lua 5.4.1?

### ISSUE THREAD

**Issue by vzhilov** [cia76/QuikPy#18]
Достаточно ли будет просто подсоединить Lua.dll версии 5.4.1? Или там необходимо сделать более масштабные изменения?

В 5.4 лучше реализована сборка мусора https://www.lua.org/manual/5.4/manual.html#2.5.2 Например, в 5.3.5 этот код потребляет неограниченное количество памяти:
```
function main()
  while true do
    sleep(100)
  end
end

function OnQuote(class, sec)
  local ql2 = getQuoteLevel2(class, sec)
end
```

**Comment by cia76** [comment]
Будет ли работать версия 5.4.1 с Квиком? Ответ на этот вопрос могут дать только разработчики Квика.

**Comment by vzhilov** [comment]
Достаточно ли будет просто подсоединить Lua.dll версии 5.4.1? Или там необходимо сделать более масштабные изменения? Похоже, что нужно переделать core.dll, иначе выдается ошибка о несоответствии версий.

**Comment by cia76** [comment]
Я не разработчик Квика. Как внутри него сделано взаимодействие с LUA, знают только они. Например, они могут использовать только заданную версию LUA. Подключение других версий будет приводить к ошибке. Возможно, потребуется модифицировать конфигурационные файлы. Или просто заменяете библиотеку, и все работает.
