### ISSUE TITLE
Расширение функционала QuikPy 

### ISSUE THREAD

**Issue by localcreator** [cia76/QuikPy#2]
Могу ли я самостоятельно получить из lua в QuikPy такие функции как getBuySellInfo и getBuySellInfoEx, которые позволяют смотреть доступна ли акция для продажи, а так же ставка риска для лонга и шорта?

**Comment by cia76** [comment]
При работе с QUIK я использую скрипты LUA из проекта https://github.com/finsight/QUIKSharp. Если в них будут реализованы функции getBuySellInfo, getBuySellInfoEx и другие, то я их также пропишу в скрипте QuikPy. Такой подход обеспечит нам обратную совместимость с QUIKSharp. Пока все нереализованные функции я оставил в QuikPy в виде комментариев.
