### ISSUE TITLE
По типам стоп-заявок, функция SendTransaction

### ISSUE THREAD

**Issue by ipARTEM** [cia76/QuikPy#20]
Доброе время суток, Игорь! Подскажите, пожалуйста, где можно узнать названия других отложенных заявок, таких как тейк-профит и прочие.
![image](https://github.com/cia76/QuikPy/assets/64425031/751f35be-ad6d-455d-8264-f281fad4e8f7)
  У нам есть 'ACTION': 'NEW_STOP_ORDER', вместо NEW_STOP_ORDER, что нужно подставить?

**Comment by cia76** [comment]
Артём, добрый день!

Найдете всё в [Руководстве пользователя Quik](https://arqatech.com/upload/iblock/df1/Doc1120.zip) Файл из архива  6. Совместная работа с другими приложениями. Пункт 6.9.3

**Comment by ipARTEM** [comment]
Отлично, спасибо большое))
