### ISSUE TITLE
Subscribe_Level_II_Quotes

### ISSUE THREAD

**Issue by poskazz** [cia76/QuikPy#21]
Привет, у тебя бага в подписках на стакан - ты вместо названия функции Subscribe_Level_II_Quotes отправляешь Subscribe_Level_2_Quotes в 539 строке. Спасибо за труды)

**Comment by cia76** [comment]
Да, в Quik# именно Subscribe_Level_II_Quotes и Unsubscribe_Level_II_Quotes. Исправил. Благодарю!
