### ISSUE TITLE
Создание более одного соединения с сервером

### ISSUE THREAD

**Issue by vzhilov** [cia76/QuikPy#3]
Здравствуйте, 

Большое Вам спасибо за этот проект. При использовании данной связки стало намного проще реализовывать торговые стратегии, нежели это было на чистом Lua.

Однако, столкнулся со следующей проблемой. Использую такую функцию (выделена в отдельный файл `functions.py`):

```
def getCandles(classCode, secCode, timeFrameName, timeFrameVal, period):
    
    from QuikPy import QuikPy

    if timeFrameName == 'H':
        timeFrame = 60*timeFrameVal
    elif timeFrameName == 'D': 
        timeFrame = 1440 
    elif timeFrameName == 'W':
        timeFrame = 10080 
    elif timeFrameName == 'MN':
        timeFrame = 23200
    else:
        timeFrame = timeFrameVal

    qpProvider = QuikPy()
    newBars = qpProvider.GetCandlesFromDataSource(classCode, secCode, timeFrame, period)["data"].copy()
    pdBars = pd.DataFrame.from_dict(pd.json_normalize(newBars), orient='columns')
    pdBars.rename(columns={'datetime.year': 'year', 'datetime.month': 'month', 'datetime.day': 'day',
                            'datetime.hour': 'hour', 'datetime.min': 'minute', 'datetime.sec': 'second'},
                    inplace=True)
    pdBars.index = pd.to_datetime(pdBars[['year', 'month', 'day', 'hour', 'minute', 'second']])
    pdBars = pdBars[['open', 'high', 'low', 'close', 'volume']]
    pdBars.index.name = 'datetime'
    pdBars.volume = pd.to_numeric(pdBars.volume, downcast='integer')
    #qpProvider.CloseConnectionAndThread()
    return pdBars
```

Далее, в другом скрипте делаю `from functions import *`. Соединение из этого скрипта проходит нормально и данные поступают. Однако, если в это время попытаться подключиться к Quik серверу из другого скрипта, то второй скрипт ждёт завершения первого. 

Придумал закрывать соединение каждый раз, после обращения скриптов к этой функции (для этого добавляю `.copy()` в получение переменной `newBars` и раскомментирую последнюю строчку перед `return`), но тогда при обращении выдается ошибка:

`OSError: [WinError 10038] An operation was attempted on something that is not a socket`

Возможно ли создание более одного соединения одновременно?

**Comment by cia76** [comment]
Приветствую вас!

Идея связки была как раз в том, чтобы из чистого Python или из открытых решений для автоторговли и тестирования типа BackTrader, работать с QUIK. Для этого используются LUA скрипты [проекта QuikSharp](https://github.com/finsight/QUIKSharp).

В скриптах используется работа с сокетами. Это не сервер в нашем представлении.

Если говорить образно, то это электрическая розетка, к которой можно подключить 1 прибор. Т.е. по дизайну подключить 2 и более клиента к этой схеме взаимодействия нельзя.

Технически, можно реализовать промежуточный уровень сервера который сам будет использовать сокеты. Клиенты будут подключаться к нему. Но тогда нужно будет четко понимать что какому клиенту передавать. Например, с одного клиента запросили подписку на минутки Газпрома, с другого запросили часовки Сбербанка. Когда серверу от Квика придут минутки/часовки, сервер должен грамотно сделать push нужному клиенту.

Я не вижу, зачем нужен такой сценарий. Когда идет автоторговля, например, через BackTrader, то клиентом будут не ваши торговые системы, а сам BackTrader. Он во всем разберется по своим правилам.

Если хотите разделить процесс тестирования и торговли, то заберите из Квика все данные для тестов (есть пример в репозитории), сохраните их локально, и работайте в тестах с ними.

**Comment by vzhilov** [comment]
Спасибо Вам за такой полный ответ. 

Нашел способ, как можно установить очередь для "розетки". Ставлю `.copy()` на строчку ниже, и потом могу смело закрыть соединение и отдать запрошенные данные. 

```
newBars = qpProvider.GetCandlesFromDataSource(classCode, secCode, timeFrame, period)["data"]
pdBars = pd.DataFrame.from_dict(pd.json_normalize(newBars), orient='columns').copy()
...
qpProvider.CloseConnectionAndThread()
return pdBars
```
    
Скприпты по очереди могут обращаться к этой функции и вроде все теперь работает как надо, спасибо.

Хотя с подписками такой способ работать не будет, это правда.
