### ISSUE TITLE
Ошибка при попытке подключения через win7

### ISSUE THREAD

**Issue by alexnisilev** [cia76/QuikPy#4]
Игорь, добрый вечер!

Большое спасибо за вашу работу!

При попытке запустить скрипт 01-Connect.py выдаёт такую ошибку: ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение - если запускаю через Jupyter

Если запускаю через консоль, выдаёт ошибку 10060 . Запускаю всё на локальном компьютере, отрубил брандмаузер. Возможно, имеет смысл какие-то другие порты указывать? Если да, то где их прописывать?

Прошу прощения, если это глупый вопрос.

С уважением, Александр

**Comment by cia76** [comment]
Александр, добрый день!

По умолчанию в примере стоит строка подключения:

`qpProvider = QuikPy(Host='192.168.1.7')  # Вызываем конструктор QuikPy с подключением к удаленному компьютеру с QUIK`

Это означает, что будет попытка подключиться к компьютеру с адресом IP 192.168.1.7 Скорее всего, у вас компьютер сидит на другом адресе. Если компьютер локальный, то закомментируйте эту строку и раскомментируйте следующую:

`qpProvider = QuikPy()  # Вызываем конструктор QuikPy с подключением к локальному компьютеру с QUIK`

Тогда все получится. Ошибка 10060 про то, что идет запрос, а в ответ - тишина :-)

**Comment by alexnisilev** [comment]
Игорь, добрый день!

Спасибо за оперативный ответ. Чекнул IP ещё раз, у меня там 192.168.0.15, вставил его, но результата нет. Удалил IP из функции - то же самое. Может быть дело в том, что я через роутер сижу? Там как-то порты и логин-пароль от локального сервака может быть надо прописать?

**Comment by cia76** [comment]
Если домашний роутер или точка доступа, то нужно просто поставить правильный IP. Также надо смотреть, есть ли софт/железки, которые фильтруют активность по портам. В QuikSharp для доступа к Квику используются порты RequestsPort=34130, CallbacksPort=34131. Надо, чтобы к этим портам на сервере доступ не был блокирован.

**Comment by alexnisilev** [comment]
Игорь, добрый вечер!

В итоге установил голую версию без обновлений и заработало. Спасибо!
