### ISSUE TITLE
Цена последней сделки

### ISSUE THREAD

**Issue by vzhilov** [cia76/QuikPy#5]
Здравствуйте, 

возможно ли получить цену последней сделки (для расчета текущих результатов по позициям) без того, чтобы подписываться на свечки или стакан, подобно тому, как это делается в LUA?

```
LUA:
x = getParamEx(CLASSCODE, SECCODE, "last").param_value
```

**Comment by cia76** [comment]
Внимательно смотрите реализованные функции. Конечно, есть.
`lastPrice = float(self.qpProvider.GetParamEx(classCode, secCode, 'LAST')['data']['param_value'])  # Последняя цена сделки`

**Comment by vzhilov** [comment]
Спасибо, разобрался. 

> Внимательно смотрите реализованные функции.

Да я бы с удовольствием, но не могу найти где смотреть. Я порылся в Quik.py и там нашел, что реализована GetParamEx, попробовал через нее и получилось. Но явного описания функций пока не нашел.

**Comment by cia76** [comment]
Смотрите, все есть в QuikPy.py
Внимательно читайте все комментарии. Их я делал не для себя, а для вас.
Например, начинается класс с такого комментария.
    """Работа с Quik из Python через LUA скрипты QuikSharp https://github.com/finsight/QUIKSharp/tree/master/src/QuikSharp/lua
     На основе Документации по языку LUA в QUIK из https://arqatech.com/ru/support/files/
     """
Ага, значит есть такая документация. Пройдите по ссылочке, найдите документ "Документации по языку LUA в QUIK ", скачайте его.

Чуть ниже в QuikPy.py есть, например, такой комментарий:
    # 3.3 Функции для получения информации по денежным средствам
Это ссылка на раздел документации. Откройте, посмотрите.

Аналогично и обратное. Смотрите документацию. Ищите в QuikPy.py по номеру раздела или названию функции. Я старался, чтобы все обозначения совпадали с оригинальной документацией.

**Comment by vzhilov** [comment]
Большое Вам спасибо.
