### ISSUE TITLE
Получение json ответа сервера при формировании транзакции

### ISSUE THREAD

**Issue by nikitabuts** [cia76/QuikPy#6]
При выполнении метода "SendTransaction" в ответе Питону выдается json, где обращаясь к ключу "data", в ответ отдается булонская переменная, не подскажете, как можно получать ответ сервера (json с различными полями/текстом ошибки от сервера) на вызов этого метода?

**Comment by cia76** [comment]
Все ответы есть в документации по Квику. В описании проекта я указал [вот эту ссылку](https://arqatech.com/ru/support/files/). Скачиваете оттуда архив **Документации по языку LUA в QUIK**. В нем есть файл **Интерпретатор языка LUA**. В нем есть вся информация по запрашиваемым и получаемым данным. Иногда, есть ссылки на другие файлы документации (например, структура tri и tro файлов).

**Comment by cia76** [comment]
Если при отправке SendTransaction из Квика возвращается ошибка, то в поле cmd вернется lua_transaction_error. Посмотреть что за ошибка пришла можно в поле lua_error. Данный функционал реализован в проекте BackTraderQuik.

**Comment by hokaspb** [comment]
File "C:\Public\workspace\QuikPy\Examples\01 - Connect.py", line 3, in <module>
    from QuikPy import QuikPy  # Работа с QUIK из Python через LUA скрипты QuikSharp
ModuleNotFoundError: No module named 'QuikPy'

Как установить модуль без Visual Studio ?   

= setup.py or pip install = not in Readme.

**Comment by cia76** [comment]
> File "C:\Public\workspace\QuikPy\Examples\01 - Connect.py", line 3, in from QuikPy import QuikPy # Работа с QUIK из Python через LUA скрипты QuikSharp ModuleNotFoundError: No module named 'QuikPy'
> 
> Как установить модуль без Visual Studio ?
> 
> = setup.py or pip install = not in Readme.

Просто скопируйте этот репозиторий. Проверяли, работает в IDLE/PyCharm/Visual Studio на любой платформе.

**Comment by hokaspb** [comment]
А без Visual Studio, например, на Rasbery PI или просто Linux проверяли ?

Я залил свой вариант на https://github.com/hokaspb/QuikPy. Посмотрите.

Исправьте Author,E-Mail в setup.py. Дайте знать, когда нужно удалить мой
форк с GitHub.

Успехов !    Владимир.             +7-921-301-32-41

пт, 25 февр. 2022 г. в 09:25, cia76 ***@***.***>:
