### ISSUE TITLE
Использование потоков 

### ISSUE THREAD

**Issue by Audorion** [cia76/QuikPy#8]
Здравствуйте. Спасибо за данную библиотеку. Хотел бы узнать больше о теме потоках при работе с Quik. Можно ли использовать здесь библиотеку threading? Будет ли у нас работать многопоточность?  Ведь как я понимаю в Quik есть только один поток.
Сейчас пишу сеточного робота с использование Tkinter и выделил основную работу робота в отдельный поток для того, чтобы обновлять информацию в интерфейсе не закрывая к нему доступ. Думал выделить еще один поток для обработок заявок. Хорошая ли это практика или это может привезти к различным проблемам?

**Comment by cia76** [comment]
Приветствую! Библиотека threading используется в QuikPy. Изначально создается 2 потока.

В первом вы будете отправлять команды и моментально получать на них отклик. Например, захотели информацию о тикере, отправили запрос, получили ответ.

Второй поток служит для обработки событий подписки. Например, вы подписались на новые бары. Как в Квике появился новый бар, он приходит в этот поток. Формируется событие прихода нового бара, которое вы можете перехватить и обрабатывать как душе угодно.

Сам Квик не подразумевает многопоточное взаимодействие. Например, нельзя 100 запросов истории разбить на 100 потоков. Все они должны быть исполнены в виде запросов через первый поток последовательно. Т.е. Квик в многопоточности является "узким местом".

**Comment by Audorion** [comment]
Спасибо за ответ! 
Мой сеточный робот смотрит на текущую последнюю цену в стакане и относительного этого продает/покупает. Хотел бы узнать является ли такой метод плохим? Я так понимаю, что лучше всего торговать при помощи подписки на свечи инструмента?

**Comment by cia76** [comment]
В примере Stream.py есть пример подписки на стакан через SubscribeLevel2Quotes. Перехватываете событие OnQuote, смотрите что пришло.

Как правильно торговать, сказать сложно. Мой вам совет. Посмотрите код QuikPy, почитайте комментарии к каждой строке. Для вас же это сделал, чтобы сразу все стало понятно. Посмотрите в описание библиотеки, по многим примерам сделал подробные видео разборы. Запустите все примеры, посмотрите, что и как работает. После уже выбирайте, что подходит под ваши системы.

**Comment by Audorion** [comment]
Спасибо за ответ!
